// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVWL7wKteTbHJds6GMzlG811WRZN_0Qwg',
    appId: '1:865426415762:web:cd9e1933368895e713064b',
    messagingSenderId: '865426415762',
    projectId: 'bahasonesia-b5ac5',
    authDomain: 'bahasonesia-b5ac5.firebaseapp.com',
    storageBucket: 'bahasonesia-b5ac5.appspot.com',
    measurementId: 'G-Q3CM69Y0EX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK3hjnIGw2xb1iwx7VLyLzWchYh1KddB8',
    appId: '1:865426415762:android:b4b8ab485d2bb9f413064b',
    messagingSenderId: '865426415762',
    projectId: 'bahasonesia-b5ac5',
    storageBucket: 'bahasonesia-b5ac5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNRs4w2Kv-rhq-WCHlOhGhdMK_-hcGveE',
    appId: '1:865426415762:ios:8be8dd855524341113064b',
    messagingSenderId: '865426415762',
    projectId: 'bahasonesia-b5ac5',
    storageBucket: 'bahasonesia-b5ac5.appspot.com',
    iosClientId: '865426415762-0cndauq0j0jtjcf5aph856u74hl4af6c.apps.googleusercontent.com',
    iosBundleId: 'com.bahaso.bahasonesiamobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNRs4w2Kv-rhq-WCHlOhGhdMK_-hcGveE',
    appId: '1:865426415762:ios:8be8dd855524341113064b',
    messagingSenderId: '865426415762',
    projectId: 'bahasonesia-b5ac5',
    storageBucket: 'bahasonesia-b5ac5.appspot.com',
    iosClientId: '865426415762-0cndauq0j0jtjcf5aph856u74hl4af6c.apps.googleusercontent.com',
    iosBundleId: 'com.bahaso.bahasonesiamobile',
  );
}
